package com.jnjuste.hospitalms.models.enums;

public enum Specialty {
    SURGEON, OPHTHALMOLOGIST, GENERAL_PRACTITIONER, RADIOLOGIST, GYNECOLOGIST, ANESTHESIOLOGIST, INTERNIST, DERMATOLOGY, CARDIOLOGIST, PUBLIC_HEALTH, ENT, PEDIATRICIAN, UROLOGIST, DENTIST, NEUROLOGIST

}
